import "../styles/globals.css";
import { CircleUserRound } from "lucide-react";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Link from "next/link";
import type { ReactNode } from "react";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`flex flex-col ${montserrat.className}`}>
        <Toaster richColors />
        <div className="flex-1">
          <Navbar />
          <div className="px-40 pt-4 h-full">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <header className="sticky top-0 z-10 bg-background">
      <nav className="flex flex-row justify-end items-center py-6 px-10 gap-10">
        <Link href="/">Home</Link>
        <Link href="/posts">Posts</Link>

        <CircleUserRound />
      </nav>
    </header>
  );
}

function Footer() {
  return (
    <footer className="flex flex-row justify-center items-center py-6 px-10">
      <p className="text-sm">Copyright © 2025 Grow</p>
    </footer>
  );
}
